name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bruna-louise16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#b84de3&color_dots=#b84de3,#e4aef7,#9e4cb7
            dist/github-contribution-grid-snake-dark.svg?color_snake=#b84de3&color_dots=#b84de3,#e4aef7,#9e4cb7
          
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
