name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bruna-louise16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#660066&color_dots=#A542CC,#9246B5,#7D3C9E,#58135E
            dist/github-contribution-grid-snake-dark.svg?color_snake=#F0A3FF&color_dots=#A542CC,#9246B5,#7D3C9E,#58135E
      
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
