name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Gera uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bruna-louise16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#ffffff&color_dots=#2e2e2e,#2e2e2e,#2e2e2e,#94209E
            dist/github-contribution-grid-snake-dark.svg?color_snake=#ffffff&color_dots=#2e2e2e,#2e2e2e,#2e2e2e,#94209E

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
