name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bruna-louise16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#FFFFFF&color_dots=#A855F7,#9333EA,#7E22CE,#6B21A8
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FFFFFF&color_dots=#A855F7,#9333EA,#7E22CE,#6B21A8
      
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
