name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bruna-louise16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#FFFFFF&color_dots=#212121,#212121,#212121,#212121&color_dots_active=#94209E
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FFFFFF&color_dots=#212121,#212121,#212121,#212121&color_dots_active=#94209E

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
