name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bruna-louise16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#8E2DE2&color_dots=#58135E,#7A1FA2,#A023AB,#D76DD8
            dist/github-contribution-grid-snake-dark.svg?color_snake=#8E2DE2&color_dots=#58135E,#7A1FA2,#A023AB,#D76DD8
          
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
